/*
 * Untron V3 Indexer API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`controller_executor_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ControllerExecutorGetError {
    UnknownValue(serde_json::Value),
}


pub async fn controller_executor_get(configuration: &configuration::Configuration, valid_from_seq: Option<&str>, valid_to_seq: Option<&str>, executor: Option<&str>, select: Option<&str>, order: Option<&str>, range: Option<&str>, range_unit: Option<&str>, offset: Option<&str>, limit: Option<&str>, prefer: Option<&str>) -> Result<Vec<models::ControllerExecutor>, Error<ControllerExecutorGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_valid_from_seq = valid_from_seq;
    let p_query_valid_to_seq = valid_to_seq;
    let p_query_executor = executor;
    let p_query_select = select;
    let p_query_order = order;
    let p_header_range = range;
    let p_header_range_unit = range_unit;
    let p_query_offset = offset;
    let p_query_limit = limit;
    let p_header_prefer = prefer;

    let uri_str = format!("{}/controller_executor", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_valid_from_seq {
        req_builder = req_builder.query(&[("valid_from_seq", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_valid_to_seq {
        req_builder = req_builder.query(&[("valid_to_seq", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_executor {
        req_builder = req_builder.query(&[("executor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_select {
        req_builder = req_builder.query(&[("select", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_range {
        req_builder = req_builder.header("Range", param_value.to_string());
    }
    if let Some(param_value) = p_header_range_unit {
        req_builder = req_builder.header("Range-Unit", param_value.to_string());
    }
    if let Some(param_value) = p_header_prefer {
        req_builder = req_builder.header("Prefer", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ControllerExecutor&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ControllerExecutor&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ControllerExecutorGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

