export const UntronV3Abi = [
  {
    type: "constructor",
    inputs: [
      { name: "controllerAddress", type: "address", internalType: "address" },
      { name: "create2Prefix", type: "bytes1", internalType: "bytes1" },
      { name: "tronReader_", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "CONTROLLER_ADDRESS",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "RECEIVER_IMPL",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SWAP_EXECUTOR",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract SwapExecutor" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bridgers",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "contract IBridger" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimsByTargetToken",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "amountUsdt", type: "uint256", internalType: "uint256" },
      { name: "leaseId", type: "uint256", internalType: "uint256" },
      { name: "targetChainId", type: "uint256", internalType: "uint256" },
      { name: "beneficiary", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createLease",
    inputs: [
      { name: "receiverSalt", type: "bytes32", internalType: "bytes32" },
      { name: "lessee", type: "address", internalType: "address" },
      { name: "nukeableAfter", type: "uint64", internalType: "uint64" },
      { name: "leaseFeePpm", type: "uint32", internalType: "uint32" },
      { name: "flatFee", type: "uint64", internalType: "uint64" },
      { name: "targetChainId", type: "uint256", internalType: "uint256" },
      { name: "targetToken", type: "address", internalType: "address" },
      { name: "beneficiary", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "leaseId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deployReceiver",
    inputs: [{ name: "salt", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "receiver", type: "address", internalType: "address payable" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositProcessed",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "effectiveLeaseRateLimit",
    inputs: [{ name: "realtor", type: "address", internalType: "address" }],
    outputs: [
      { name: "enabled", type: "bool", internalType: "bool" },
      { name: "maxLeases", type: "uint256", internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1", internalType: "bytes1" },
      { name: "name", type: "string", internalType: "string" },
      { name: "version", type: "string", internalType: "string" },
      { name: "chainId", type: "uint256", internalType: "uint256" },
      { name: "verifyingContract", type: "address", internalType: "address" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
      { name: "extensions", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eventChainTip",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fill",
    inputs: [
      { name: "targetToken", type: "address", internalType: "address" },
      { name: "maxClaims", type: "uint256", internalType: "uint256" },
      {
        name: "calls",
        type: "tuple[]",
        internalType: "struct Call[]",
        components: [
          { name: "to", type: "address", internalType: "address" },
          { name: "value", type: "uint256", internalType: "uint256" },
          { name: "data", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isChainDeprecated",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isRealtor",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastControllerEventTip",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastReceiverPullTimestamp",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "leaseNonces",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "leases",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "receiverSalt", type: "bytes32", internalType: "bytes32" },
      { name: "realtor", type: "address", internalType: "address" },
      { name: "lessee", type: "address", internalType: "address" },
      { name: "startTime", type: "uint64", internalType: "uint64" },
      { name: "nukeableAfter", type: "uint64", internalType: "uint64" },
      { name: "leaseFeePpm", type: "uint32", internalType: "uint32" },
      { name: "flatFee", type: "uint64", internalType: "uint64" },
      { name: "recognizedRaw", type: "uint256", internalType: "uint256" },
      { name: "backedRaw", type: "uint256", internalType: "uint256" },
      { name: "unbackedRaw", type: "uint256", internalType: "uint256" },
      {
        name: "payout",
        type: "tuple",
        internalType: "struct UntronV3.PayoutConfig",
        components: [
          { name: "targetChainId", type: "uint256", internalType: "uint256" },
          { name: "targetToken", type: "address", internalType: "address" },
          { name: "beneficiary", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lesseePayoutConfigRateLimit",
    inputs: [],
    outputs: [
      { name: "maxUpdates", type: "uint256", internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lpPrincipal",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextControllerEventIndex",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextIndexByTargetToken",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextLeaseId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "result", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  { type: "function", name: "pause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "preEntitle",
    inputs: [
      { name: "receiverSalt", type: "bytes32", internalType: "bytes32" },
      { name: "tronBlockNumber", type: "uint256", internalType: "uint256" },
      { name: "encodedTx", type: "bytes", internalType: "bytes" },
      { name: "proof", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "index", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "claimIndex", type: "uint256", internalType: "uint256" },
      { name: "leaseId", type: "uint256", internalType: "uint256" },
      { name: "netOut", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "predictReceiverAddress",
    inputs: [{ name: "salt", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "predicted", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "predictReceiverAddress",
    inputs: [
      { name: "controller", type: "address", internalType: "address" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "predicted", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "processControllerEvents",
    inputs: [{ name: "maxEvents", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "protocolFloorPpm",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolLeaseRateLimit",
    inputs: [],
    outputs: [
      { name: "maxLeases", type: "uint256", internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolPnl",
    inputs: [],
    outputs: [{ name: "", type: "int256", internalType: "int256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "realtorLeaseRateLimit",
    inputs: [{ name: "realtor", type: "address", internalType: "address" }],
    outputs: [
      { name: "mode", type: "uint8", internalType: "enum UntronV3.LeaseRateLimitMode" },
      { name: "maxLeases", type: "uint256", internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "realtorMinFeePpm",
    inputs: [{ name: "realtor", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "receiverBytecode",
    inputs: [],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "relayControllerEventChain",
    inputs: [
      { name: "tronBlockNumber", type: "uint256", internalType: "uint256" },
      { name: "encodedTx", type: "bytes", internalType: "bytes" },
      { name: "proof", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "index", type: "uint256", internalType: "uint256" },
      {
        name: "events",
        type: "tuple[]",
        internalType: "struct UntronV3.ControllerEvent[]",
        components: [
          { name: "sig", type: "bytes32", internalType: "bytes32" },
          { name: "data", type: "bytes", internalType: "bytes" },
          { name: "blockNumber", type: "uint64", internalType: "uint64" },
          { name: "blockTimestamp", type: "uint64", internalType: "uint64" },
        ],
      },
    ],
    outputs: [{ name: "tipNew", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "rescueTokens",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setBridger",
    inputs: [
      { name: "targetToken", type: "address", internalType: "address" },
      { name: "targetChainId", type: "uint256", internalType: "uint256" },
      { name: "bridger", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setChainDeprecated",
    inputs: [
      { name: "targetChainId", type: "uint256", internalType: "uint256" },
      { name: "deprecated", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLesseePayoutConfigRateLimit",
    inputs: [
      { name: "maxUpdates", type: "uint256", internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPayoutConfig",
    inputs: [
      { name: "leaseId", type: "uint256", internalType: "uint256" },
      { name: "targetChainId", type: "uint256", internalType: "uint256" },
      { name: "targetToken", type: "address", internalType: "address" },
      { name: "beneficiary", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPayoutConfigWithSig",
    inputs: [
      { name: "leaseId", type: "uint256", internalType: "uint256" },
      {
        name: "config",
        type: "tuple",
        internalType: "struct UntronV3.PayoutConfig",
        components: [
          { name: "targetChainId", type: "uint256", internalType: "uint256" },
          { name: "targetToken", type: "address", internalType: "address" },
          { name: "beneficiary", type: "address", internalType: "address" },
        ],
      },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setProtocolFloorPpm",
    inputs: [{ name: "floorPpm", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setProtocolLeaseRateLimit",
    inputs: [
      { name: "maxLeases", type: "uint256", internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRealtor",
    inputs: [
      { name: "realtor", type: "address", internalType: "address" },
      { name: "allowed", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRealtorLeaseRateLimit",
    inputs: [
      { name: "realtor", type: "address", internalType: "address" },
      { name: "mode", type: "uint8", internalType: "enum UntronV3.LeaseRateLimitMode" },
      { name: "maxLeases", type: "uint256", internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRealtorMinFeePpm",
    inputs: [
      { name: "realtor", type: "address", internalType: "address" },
      { name: "minFeePpm", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSwapRate",
    inputs: [
      { name: "targetToken", type: "address", internalType: "address" },
      { name: "ratePpm", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTronReader",
    inputs: [{ name: "reader", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUsdt",
    inputs: [{ name: "usdt_", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "swapRatePpm",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "tronReader",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract TronTxReader" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tronUsdt",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  { type: "function", name: "unpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "usdt",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdtBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawProtocolProfit",
    inputs: [{ name: "amount", type: "int256", internalType: "int256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "BridgerSet",
    inputs: [
      { name: "targetToken", type: "address", indexed: true, internalType: "address" },
      { name: "targetChainId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "bridger", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChainDeprecatedSet",
    inputs: [
      { name: "targetChainId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "deprecated", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ClaimCreated",
    inputs: [
      { name: "claimIndex", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "leaseId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "amountUsdt", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ClaimFilled",
    inputs: [
      { name: "claimIndex", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "leaseId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "amountUsdt", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ControllerEventChainTipUpdated",
    inputs: [
      { name: "previousTip", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "blockNumber", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "blockTimestamp", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "eventSignature", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "abiEncodedEventData", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ControllerEventProcessed",
    inputs: [
      { name: "eventIndex", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "blockNumber", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "blockTimestamp", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "eventSignature", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "abiEncodedEventData", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DepositPreEntitled",
    inputs: [
      { name: "txId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "leaseId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "rawAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "netOut", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LeaseCreated",
    inputs: [
      { name: "leaseId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "receiverSalt", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "realtor", type: "address", indexed: false, internalType: "address" },
      { name: "lessee", type: "address", indexed: false, internalType: "address" },
      { name: "startTime", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "nukeableAfter", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "leaseFeePpm", type: "uint32", indexed: false, internalType: "uint32" },
      { name: "flatFee", type: "uint64", indexed: false, internalType: "uint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LeaseNonceUpdated",
    inputs: [
      { name: "leaseId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "nonce", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LesseePayoutConfigRateLimitSet",
    inputs: [
      { name: "maxUpdates", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LpDeposited",
    inputs: [
      { name: "lp", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LpWithdrawn",
    inputs: [
      { name: "lp", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "oldOwner", type: "address", indexed: true, internalType: "address" },
      { name: "newOwner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PayoutConfigUpdated",
    inputs: [
      { name: "leaseId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "targetChainId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "targetToken", type: "address", indexed: false, internalType: "address" },
      { name: "beneficiary", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolFloorSet",
    inputs: [{ name: "floorPpm", type: "uint256", indexed: false, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolLeaseRateLimitSet",
    inputs: [
      { name: "maxLeases", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolPnlUpdated",
    inputs: [
      { name: "pnl", type: "int256", indexed: false, internalType: "int256" },
      { name: "delta", type: "int256", indexed: false, internalType: "int256" },
      {
        name: "reason",
        type: "uint8",
        indexed: false,
        internalType: "enum UntronV3Index.PnlReason",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RealtorLeaseRateLimitSet",
    inputs: [
      { name: "realtor", type: "address", indexed: true, internalType: "address" },
      { name: "mode", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "maxLeases", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "windowSeconds", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RealtorMinFeeSet",
    inputs: [
      { name: "realtor", type: "address", indexed: true, internalType: "address" },
      { name: "minFeePpm", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RealtorSet",
    inputs: [
      { name: "realtor", type: "address", indexed: true, internalType: "address" },
      { name: "allowed", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SwapRateSet",
    inputs: [
      { name: "targetToken", type: "address", indexed: true, internalType: "address" },
      { name: "ratePpm", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokensRescued",
    inputs: [
      { name: "token", type: "address", indexed: false, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TronReaderSet",
    inputs: [{ name: "reader", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "TronUsdtSet",
    inputs: [{ name: "tronUsdt", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "UsdtSet",
    inputs: [{ name: "usdt", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  { type: "error", name: "AlreadyInitialized", inputs: [] },
  { type: "error", name: "AmountTooLargeForInt", inputs: [] },
  { type: "error", name: "CannotRescueUSDT", inputs: [] },
  { type: "error", name: "ChainDeprecated", inputs: [] },
  { type: "error", name: "DepositAlreadyProcessed", inputs: [] },
  { type: "error", name: "DepositNotAfterLastReceiverPull", inputs: [] },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "EventRelayNoProgress", inputs: [] },
  { type: "error", name: "EventTipMismatch", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "InsufficientProtocolProfit", inputs: [] },
  { type: "error", name: "InsufficientUsdtBalance", inputs: [] },
  { type: "error", name: "InvalidLeaseId", inputs: [] },
  { type: "error", name: "InvalidLeaseTimeframe", inputs: [] },
  { type: "error", name: "InvalidReceiverForSalt", inputs: [] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "InvalidTargetToken", inputs: [] },
  { type: "error", name: "LeaseFeeTooLow", inputs: [] },
  { type: "error", name: "LeaseNotNukeableYet", inputs: [] },
  { type: "error", name: "LeaseRateLimitConfigInvalid", inputs: [] },
  { type: "error", name: "LeaseRateLimitExceeded", inputs: [] },
  { type: "error", name: "NewOwnerIsZeroAddress", inputs: [] },
  { type: "error", name: "NoActiveLease", inputs: [] },
  { type: "error", name: "NoBridger", inputs: [] },
  { type: "error", name: "NoEventChainTipInMulticall", inputs: [] },
  { type: "error", name: "NotATrc20Transfer", inputs: [] },
  { type: "error", name: "NotEventChainTip", inputs: [] },
  { type: "error", name: "NotLessee", inputs: [] },
  { type: "error", name: "NotRealtor", inputs: [] },
  { type: "error", name: "NotTronUsdt", inputs: [] },
  { type: "error", name: "PayoutConfigRateLimitConfigInvalid", inputs: [] },
  { type: "error", name: "PayoutConfigRateLimitExceeded", inputs: [] },
  { type: "error", name: "RateNotSet", inputs: [] },
  { type: "error", name: "Reentrancy", inputs: [] },
  { type: "error", name: "SignatureExpired", inputs: [] },
  { type: "error", name: "TronInvalidCalldataLength", inputs: [] },
  { type: "error", name: "TronInvalidCalldataLength", inputs: [] },
  { type: "error", name: "TronInvalidTrc20DataLength", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "WithdrawExceedsPrincipal", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
] as const;
