export const UntronControllerAbi = [
  {
    type: "constructor",
    inputs: [{ name: "create2Prefix", type: "bytes1", internalType: "bytes1" }],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "RECEIVER_IMPL",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deployReceiver",
    inputs: [{ name: "salt", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "receiver", type: "address", internalType: "address payable" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "eventChainTip",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executor",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isEventChainTip",
    inputs: [{ name: "eventChainTip_", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lp",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lpExchangeRateFor",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lpWithdrawTokens",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "multicall",
    inputs: [{ name: "data", type: "bytes[]", internalType: "bytes[]" }],
    outputs: [{ name: "", type: "bytes[]", internalType: "bytes[]" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "payloadFor",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "predictReceiverAddress",
    inputs: [{ name: "salt", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "predicted", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "predictReceiverAddress",
    inputs: [
      { name: "controller", type: "address", internalType: "address" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "predicted", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pullFromReceivers",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "receiverSalts", type: "bytes32[]", internalType: "bytes32[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pulledUsdt",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rebalanceUsdt",
    inputs: [
      { name: "rebalancer", type: "address", internalType: "address" },
      { name: "inAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "receiverBytecode",
    inputs: [],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setExecutor",
    inputs: [{ name: "_executor", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLp",
    inputs: [{ name: "_lp", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLpExchangeRate",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "exchangeRate", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOwner",
    inputs: [{ name: "_newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPayload",
    inputs: [
      { name: "_rebalancer", type: "address", internalType: "address" },
      { name: "_payload", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUsdt",
    inputs: [{ name: "_usdt", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferUsdtFromController",
    inputs: [
      { name: "recipient", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usdt",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "ControllerUsdtTransfer",
    inputs: [
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExecutorChanged",
    inputs: [{ name: "newExecutor", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "LpExchangeRateSet",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "exchangeRate", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LpSet",
    inputs: [{ name: "newLp", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "LpTokensWithdrawn",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnerChanged",
    inputs: [{ name: "newOwner", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "PayloadSet",
    inputs: [
      { name: "rebalancer", type: "address", indexed: true, internalType: "address" },
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PulledFromReceiver",
    inputs: [
      { name: "receiverSalt", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "tokenAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "exchangeRate", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "usdtAmount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReceiverDeployed",
    inputs: [
      { name: "receiver", type: "address", indexed: true, internalType: "address" },
      { name: "salt", type: "bytes32", indexed: false, internalType: "bytes32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UsdtRebalanced",
    inputs: [
      { name: "inAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "outAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "rebalancer", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UsdtSet",
    inputs: [{ name: "newUsdt", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  { type: "error", name: "ExchangeRateMismatch", inputs: [] },
  { type: "error", name: "InsufficientLpLiquidity", inputs: [] },
  { type: "error", name: "InsufficientPulledAmount", inputs: [] },
  { type: "error", name: "OnlyExecutor", inputs: [] },
  { type: "error", name: "OnlyLp", inputs: [] },
  { type: "error", name: "OnlyOwner", inputs: [] },
  { type: "error", name: "OutAmountMismatch", inputs: [] },
  { type: "error", name: "RouteNotSet", inputs: [] },
  { type: "error", name: "ZeroOwnerAddress", inputs: [] },
] as const;
