export const TronLightClientAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "blockRangeProver", type: "address", internalType: "contract IBlockRangeProver" },
      { name: "initialBlockHash", type: "bytes32", internalType: "bytes32" },
      { name: "initialTxTrieRoot", type: "bytes32", internalType: "bytes32" },
      { name: "initialTimestamp", type: "uint32", internalType: "uint32" },
      { name: "_srs", type: "bytes20[27]", internalType: "bytes20[27]" },
      { name: "_witnessDelegatees", type: "bytes20[27]", internalType: "bytes20[27]" },
      { name: "srDataHash", type: "bytes32", internalType: "bytes32" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BLOCK_RANGE_PROVER",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IBlockRangeProver" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SR_DATA_HASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eventChainTip",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBlockId",
    inputs: [{ name: "blockNumber", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "blockId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBlockTimestamp",
    inputs: [{ name: "blockNumber", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "timestamp", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTxTrieRoot",
    inputs: [{ name: "blockNumber", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "txTrieRoot", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "latestProvenBlock",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proveBlockRange",
    inputs: [
      { name: "startingBlock", type: "bytes32", internalType: "bytes32" },
      { name: "endingBlock", type: "bytes32", internalType: "bytes32" },
      { name: "endingBlockTxTrieRoot", type: "bytes32", internalType: "bytes32" },
      { name: "endingBlockTimestamp", type: "uint32", internalType: "uint32" },
      { name: "zkProof", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "proveBlocks",
    inputs: [
      { name: "startingBlock", type: "bytes32", internalType: "bytes32" },
      { name: "compressedTronBlockMetadata", type: "bytes", internalType: "bytes" },
      { name: "compressedSignatures", type: "bytes", internalType: "bytes" },
      { name: "intersectionOffset", type: "uint256", internalType: "uint256" },
      { name: "storeOffsets16", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "srs",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "sr", type: "bytes20", internalType: "bytes20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "witnessDelegatees",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "delegatee", type: "bytes20", internalType: "bytes20" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "LatestProvenBlockUpdated",
    inputs: [
      { name: "previousLatest", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "newLatest", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "newBlockNumber", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TronBlockStored",
    inputs: [
      { name: "blockNumber", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "blockId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "txTrieRoot", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "timestamp", type: "uint32", indexed: false, internalType: "uint32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TronLightClientConfigured",
    inputs: [
      { name: "blockRangeProver", type: "address", indexed: true, internalType: "address" },
      { name: "srDataHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "initialBlockId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "delegateeGroupsPacked", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "initialTxTrieRoot", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "initialTimestamp", type: "uint32", indexed: false, internalType: "uint32" },
      { name: "srs", type: "bytes20[27]", indexed: false, internalType: "bytes20[27]" },
      {
        name: "witnessDelegatees",
        type: "bytes20[27]",
        indexed: false,
        internalType: "bytes20[27]",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BlockNotRelayed", inputs: [] },
  { type: "error", name: "BlockTooOld", inputs: [] },
  { type: "error", name: "InvalidChain", inputs: [] },
  { type: "error", name: "InvalidCompressedSignaturesLength", inputs: [] },
  { type: "error", name: "InvalidCompressedTronBlockMetadataLength", inputs: [] },
  {
    type: "error",
    name: "InvalidIntersectionClaim",
    inputs: [
      { name: "blockNumber", type: "uint256", internalType: "uint256" },
      { name: "blockId", type: "bytes32", internalType: "bytes32" },
    ],
  },
  {
    type: "error",
    name: "InvalidIntersectionOffset",
    inputs: [
      { name: "intersectionOffset", type: "uint256", internalType: "uint256" },
      { name: "numBlocks", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidParentBlockId",
    inputs: [
      { name: "yours", type: "bytes32", internalType: "bytes32" },
      { name: "real", type: "bytes32", internalType: "bytes32" },
    ],
  },
  {
    type: "error",
    name: "InvalidSrIndex",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "InvalidStoreOffset",
    inputs: [
      { name: "offset", type: "uint256", internalType: "uint256" },
      { name: "numBlocks", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidWitnessDelegateeIndex",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "InvalidWitnessSigner", inputs: [] },
  { type: "error", name: "Sha256PrecompileFailed", inputs: [] },
  {
    type: "error",
    name: "StoreOffsetsNotStrictlyIncreasing",
    inputs: [
      { name: "prev", type: "uint256", internalType: "uint256" },
      { name: "next", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "TooManyBlocks",
    inputs: [{ name: "numBlocks", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "UnanchoredBlockRange", inputs: [] },
  {
    type: "error",
    name: "WitnessProducedRecently",
    inputs: [{ name: "signer", type: "bytes20", internalType: "bytes20" }],
  },
] as const;
