/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventAppended : Canonical raw EventAppended stream (both hub + controller)  This is the canonical ordered stream of Untron \"semantic events\", as emitted by the onchain index contracts. Each row corresponds to one onchain `EventAppended` log and includes: - hash-chain linkage (prev_tip/new_tip/event_seq) - the semantic event name (`event_type`) and decoded arguments (`args`) - block/tx metadata for auditability  This view filters to `canonical=true` only.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventAppended {
    /// Which stream emitted this EventAppended log (`hub` or `controller`)
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<Stream>,
    /// Monotonic sequence number in the stream's onchain event hash-chain
    #[serde(rename = "event_seq", skip_serializing_if = "Option::is_none")]
    pub event_seq: Option<i64>,
    /// Previous onchain event hash-chain tip before this event
    #[serde(rename = "prev_tip", skip_serializing_if = "Option::is_none")]
    pub prev_tip: Option<String>,
    /// New onchain event hash-chain tip after this event
    #[serde(rename = "new_tip", skip_serializing_if = "Option::is_none")]
    pub new_tip: Option<String>,
    /// Keccak256 hash of the semantic event signature string (bytes32 hex)
    #[serde(rename = "event_signature", skip_serializing_if = "Option::is_none")]
    pub event_signature: Option<String>,
    /// Exact ABI-encoded event payload bytes that were hashed onchain (0x hex)
    #[serde(rename = "abi_encoded_event_data", skip_serializing_if = "Option::is_none")]
    pub abi_encoded_event_data: Option<String>,
    /// Worker-decoded semantic event name (e.g. `LeaseCreated`, `ClaimCreated`)
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    /// Worker-decoded event arguments as JSON (snake_case keys; values as strings/hex)
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<serde_json::Value>,
    /// Block number containing the EventAppended log
    #[serde(rename = "block_number", skip_serializing_if = "Option::is_none")]
    pub block_number: Option<i64>,
    /// Block timestamp (seconds since epoch) containing the EventAppended log
    #[serde(rename = "block_timestamp", skip_serializing_if = "Option::is_none")]
    pub block_timestamp: Option<i64>,
    /// Convenience timestamp (block_timestamp converted to timestamptz)
    #[serde(rename = "block_time", skip_serializing_if = "Option::is_none")]
    pub block_time: Option<String>,
    /// Block hash of the log's block (bytes32 hex)
    #[serde(rename = "block_hash", skip_serializing_if = "Option::is_none")]
    pub block_hash: Option<String>,
    /// Transaction hash of the log's transaction (bytes32 hex)
    #[serde(rename = "tx_hash", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<String>,
    /// Log index within the transaction receipt (0-based)
    #[serde(rename = "log_index", skip_serializing_if = "Option::is_none")]
    pub log_index: Option<i64>,
}

impl EventAppended {
    /// Canonical raw EventAppended stream (both hub + controller)  This is the canonical ordered stream of Untron \"semantic events\", as emitted by the onchain index contracts. Each row corresponds to one onchain `EventAppended` log and includes: - hash-chain linkage (prev_tip/new_tip/event_seq) - the semantic event name (`event_type`) and decoded arguments (`args`) - block/tx metadata for auditability  This view filters to `canonical=true` only.
    pub fn new() -> EventAppended {
        EventAppended {
            stream: None,
            event_seq: None,
            prev_tip: None,
            new_tip: None,
            event_signature: None,
            abi_encoded_event_data: None,
            event_type: None,
            args: None,
            block_number: None,
            block_timestamp: None,
            block_time: None,
            block_hash: None,
            tx_hash: None,
            log_index: None,
        }
    }
}
/// Which stream emitted this EventAppended log (`hub` or `controller`)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Stream {
    #[serde(rename = "hub")]
    Hub,
    #[serde(rename = "controller")]
    Controller,
}

impl Default for Stream {
    fn default() -> Stream {
        Self::Hub
    }
}

