/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HubProtocolConfig : Current hub protocol configuration (singleton)  Derived from a set of hub config events (USDT, Tron reader, fee floors, rate limits).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubProtocolConfig {
    /// Event sequence at which this config snapshot became current  Note: This is a Primary Key.<pk/>
    #[serde(rename = "valid_from_seq", skip_serializing_if = "Option::is_none")]
    pub valid_from_seq: Option<i64>,
    #[serde(rename = "valid_to_seq", skip_serializing_if = "Option::is_none")]
    pub valid_to_seq: Option<i64>,
    /// EVM USDT accounting token address on the hub chain
    #[serde(rename = "usdt", skip_serializing_if = "Option::is_none")]
    pub usdt: Option<String>,
    /// Tron USDT TRC-20 contract address (base58) accepted by `preEntitle`
    #[serde(rename = "tron_usdt", skip_serializing_if = "Option::is_none")]
    pub tron_usdt: Option<String>,
    /// Trusted Tron transaction reader address used to verify + decode Tron transactions
    #[serde(rename = "tron_reader", skip_serializing_if = "Option::is_none")]
    pub tron_reader: Option<String>,
    /// Protocol-wide minimum percentage fee floor (ppm)
    #[serde(rename = "floor_ppm", skip_serializing_if = "Option::is_none")]
    pub floor_ppm: Option<i64>,
    /// Protocol-wide minimum flat fee floor (USDT units)
    #[serde(rename = "floor_flat_fee", skip_serializing_if = "Option::is_none")]
    pub floor_flat_fee: Option<serde_json::Number>,
    /// Protocol-wide maximum lease duration in seconds (NULL/0 means disabled)
    #[serde(rename = "max_lease_duration_seconds", skip_serializing_if = "Option::is_none")]
    pub max_lease_duration_seconds: Option<i64>,
    /// Max payout config updates allowed per window per lessee (NULL/0 means disabled)
    #[serde(rename = "lessee_rate_max_updates", skip_serializing_if = "Option::is_none")]
    pub lessee_rate_max_updates: Option<serde_json::Number>,
    /// Window size (seconds) for payout config update rate limiting (NULL/0 means disabled)
    #[serde(rename = "lessee_rate_window_seconds", skip_serializing_if = "Option::is_none")]
    pub lessee_rate_window_seconds: Option<serde_json::Number>,
}

impl HubProtocolConfig {
    /// Current hub protocol configuration (singleton)  Derived from a set of hub config events (USDT, Tron reader, fee floors, rate limits).
    pub fn new() -> HubProtocolConfig {
        HubProtocolConfig {
            valid_from_seq: None,
            valid_to_seq: None,
            usdt: None,
            tron_usdt: None,
            tron_reader: None,
            floor_ppm: None,
            floor_flat_fee: None,
            max_lease_duration_seconds: None,
            lessee_rate_max_updates: None,
            lessee_rate_window_seconds: None,
        }
    }
}

