/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HubPayoutConfigs : Current payout configuration per lease (KV)  Defines destination chain, settlement token, and beneficiary for newly created claims under each lease.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubPayoutConfigs {
    /// Lease id this payout config applies to  Note: This is a Primary Key.<pk/>
    #[serde(rename = "lease_id", skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<serde_json::Number>,
    /// Event sequence at which this payout config became current  Note: This is a Primary Key.<pk/>
    #[serde(rename = "valid_from_seq", skip_serializing_if = "Option::is_none")]
    pub valid_from_seq: Option<i64>,
    #[serde(rename = "valid_to_seq", skip_serializing_if = "Option::is_none")]
    pub valid_to_seq: Option<i64>,
    /// Destination chainId for payouts created under this config
    #[serde(rename = "target_chain_id", skip_serializing_if = "Option::is_none")]
    pub target_chain_id: Option<i64>,
    /// Settlement token on the hub chain used for fills (USDT or swapped token)
    #[serde(rename = "target_token", skip_serializing_if = "Option::is_none")]
    pub target_token: Option<String>,
    /// Recipient (EVM) for payouts / bridged delivery
    #[serde(rename = "beneficiary", skip_serializing_if = "Option::is_none")]
    pub beneficiary: Option<String>,
}

impl HubPayoutConfigs {
    /// Current payout configuration per lease (KV)  Defines destination chain, settlement token, and beneficiary for newly created claims under each lease.
    pub fn new() -> HubPayoutConfigs {
        HubPayoutConfigs {
            lease_id: None,
            valid_from_seq: None,
            valid_to_seq: None,
            target_chain_id: None,
            target_token: None,
            beneficiary: None,
        }
    }
}

