/*
 * Untron V3 Indexer API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HubProtocolPnl : Current protocol PnL snapshot (singleton)  Tracks fee revenue and rebalance/withdrawal deltas as emitted by the hub contract.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubProtocolPnl {
    /// Event sequence at which this PnL snapshot became current  Note: This is a Primary Key.<pk/>
    #[serde(rename = "valid_from_seq", skip_serializing_if = "Option::is_none")]
    pub valid_from_seq: Option<i64>,
    #[serde(rename = "valid_to_seq", skip_serializing_if = "Option::is_none")]
    pub valid_to_seq: Option<i64>,
    /// Current protocol PnL value (int256)
    #[serde(rename = "pnl", skip_serializing_if = "Option::is_none")]
    pub pnl: Option<serde_json::Number>,
    /// Delta applied at this event (int256)
    #[serde(rename = "delta", skip_serializing_if = "Option::is_none")]
    pub delta: Option<serde_json::Number>,
    /// PnL reason code (matches `UntronV3Index.PnlReason`)
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<i64>,
}

impl HubProtocolPnl {
    /// Current protocol PnL snapshot (singleton)  Tracks fee revenue and rebalance/withdrawal deltas as emitted by the hub contract.
    pub fn new() -> HubProtocolPnl {
        HubProtocolPnl {
            valid_from_seq: None,
            valid_to_seq: None,
            pnl: None,
            delta: None,
            reason: None,
        }
    }
}

