/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HubClaims : Current claim states (KV)  Claims are created by proven Tron deposits / LP-sponsored subjective pre-entitlement / controller profit volume, and transition to `filled` when a filler settles them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubClaims {
    /// Lease id that produced this claim  Note: This is a Primary Key.<pk/>
    #[serde(rename = "lease_id", skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<serde_json::Number>,
    /// Per-lease claim id (uint256, 0-indexed)  Note: This is a Primary Key.<pk/>
    #[serde(rename = "claim_id", skip_serializing_if = "Option::is_none")]
    pub claim_id: Option<serde_json::Number>,
    /// Event sequence at which this claim version became current  Note: This is a Primary Key.<pk/>
    #[serde(rename = "valid_from_seq", skip_serializing_if = "Option::is_none")]
    pub valid_from_seq: Option<i64>,
    #[serde(rename = "valid_to_seq", skip_serializing_if = "Option::is_none")]
    pub valid_to_seq: Option<i64>,
    /// Token used for settlement when filling this claim (EVM on hub chain)
    #[serde(rename = "target_token", skip_serializing_if = "Option::is_none")]
    pub target_token: Option<String>,
    /// Index in the FIFO queue (per target_token) where this claim was enqueued
    #[serde(rename = "queue_index", skip_serializing_if = "Option::is_none")]
    pub queue_index: Option<serde_json::Number>,
    /// USDT-denominated claim amount (uint256) used for accounting
    #[serde(rename = "amount_usdt", skip_serializing_if = "Option::is_none")]
    pub amount_usdt: Option<serde_json::Number>,
    /// Destination chainId for payout (local if equals hub chainId)
    #[serde(rename = "target_chain_id", skip_serializing_if = "Option::is_none")]
    pub target_chain_id: Option<i64>,
    /// Beneficiary address (EVM) receiving payout
    #[serde(rename = "beneficiary", skip_serializing_if = "Option::is_none")]
    pub beneficiary: Option<String>,
    /// Claim origin code (matches `UntronV3Index.ClaimOrigin`)
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<i64>,
    /// Origin identifier (txId for pre-entitle, receiver_salt for receiver pull, etc.)
    #[serde(rename = "origin_id", skip_serializing_if = "Option::is_none")]
    pub origin_id: Option<String>,
    /// Origin actor (e.g. subjective pre-entitle sponsor; otherwise zero)
    #[serde(rename = "origin_actor", skip_serializing_if = "Option::is_none")]
    pub origin_actor: Option<String>,
    /// Origin token/address (Tron token for receiver pull; zero address otherwise)
    #[serde(rename = "origin_token", skip_serializing_if = "Option::is_none")]
    pub origin_token: Option<String>,
    /// Origin timestamp (seconds) (Tron block time or controller dump time; 0 if not applicable)
    #[serde(rename = "origin_timestamp", skip_serializing_if = "Option::is_none")]
    pub origin_timestamp: Option<i64>,
    /// Raw amount before fees (USDT-equivalent units)
    #[serde(rename = "origin_raw_amount", skip_serializing_if = "Option::is_none")]
    pub origin_raw_amount: Option<serde_json::Number>,
    /// Claim lifecycle status (`created` or `filled`)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl HubClaims {
    /// Current claim states (KV)  Claims are created by proven Tron deposits / LP-sponsored subjective pre-entitlement / controller profit volume, and transition to `filled` when a filler settles them.
    pub fn new() -> HubClaims {
        HubClaims {
            lease_id: None,
            claim_id: None,
            valid_from_seq: None,
            valid_to_seq: None,
            target_token: None,
            queue_index: None,
            amount_usdt: None,
            target_chain_id: None,
            beneficiary: None,
            origin: None,
            origin_id: None,
            origin_actor: None,
            origin_token: None,
            origin_timestamp: None,
            origin_raw_amount: None,
            status: None,
        }
    }
}
/// Claim lifecycle status (`created` or `filled`)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "filled")]
    Filled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Created
    }
}

