/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HubLpAllowlist : Current LP allowlist (KV)  LPs must be allowlisted to deposit principal into the hub fast-fill vault.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HubLpAllowlist {
    /// LP address (EVM)  Note: This is a Primary Key.<pk/>
    #[serde(rename = "lp", skip_serializing_if = "Option::is_none")]
    pub lp: Option<String>,
    /// Event sequence at which this allowlist entry became current  Note: This is a Primary Key.<pk/>
    #[serde(rename = "valid_from_seq", skip_serializing_if = "Option::is_none")]
    pub valid_from_seq: Option<i64>,
    #[serde(rename = "valid_to_seq", skip_serializing_if = "Option::is_none")]
    pub valid_to_seq: Option<i64>,
    /// Whether this LP may deposit into the fast-fill vault (withdrawals are always allowed)
    #[serde(rename = "allowed", skip_serializing_if = "Option::is_none")]
    pub allowed: Option<bool>,
}

impl HubLpAllowlist {
    /// Current LP allowlist (KV)  LPs must be allowlisted to deposit principal into the hub fast-fill vault.
    pub fn new() -> HubLpAllowlist {
        HubLpAllowlist {
            lp: None,
            valid_from_seq: None,
            valid_to_seq: None,
            allowed: None,
        }
    }
}

