/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiverUsdtTransferActionability : Receiver USDT deposits + actionability hints (preEntitle vs pull)  For each canonical TRC-20 USDT transfer into a deterministic receiver, this view shows: - whether the hub has already accounted for it (matching claim origin_id == tx_hash), - the latest observed receiver pull timestamp for (receiver_salt, token), and - whether `preEntitle` is still time-eligible (`transfer_ts > last_pull_ts`).  `recommended_action` is a best-effort operator hint: - 'already_accounted' => hub claim exists (origin pre-entitle or subjective pre-entitle) - 'pre_entitle'        => no claim yet and pre-entitle timing is still allowed - 'pull'               => no claim yet and a later pull timestamp suggests pre-entitle would revert
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiverUsdtTransferActionability {
    #[serde(rename = "chain_id", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<i32>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "receiver_salt", skip_serializing_if = "Option::is_none")]
    pub receiver_salt: Option<String>,
    #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
    pub sender: Option<String>,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    #[serde(rename = "block_number", skip_serializing_if = "Option::is_none")]
    pub block_number: Option<i32>,
    #[serde(rename = "block_timestamp", skip_serializing_if = "Option::is_none")]
    pub block_timestamp: Option<i32>,
    #[serde(rename = "block_time", skip_serializing_if = "Option::is_none")]
    pub block_time: Option<String>,
    #[serde(rename = "block_hash", skip_serializing_if = "Option::is_none")]
    pub block_hash: Option<String>,
    #[serde(rename = "tx_hash", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<String>,
    #[serde(rename = "log_index", skip_serializing_if = "Option::is_none")]
    pub log_index: Option<i32>,
    #[serde(rename = "claim_origin", skip_serializing_if = "Option::is_none")]
    pub claim_origin: Option<i32>,
    #[serde(rename = "claim_lease_id", skip_serializing_if = "Option::is_none")]
    pub claim_lease_id: Option<f64>,
    #[serde(rename = "claim_id", skip_serializing_if = "Option::is_none")]
    pub claim_id: Option<f64>,
    #[serde(rename = "claim_status", skip_serializing_if = "Option::is_none")]
    pub claim_status: Option<ClaimStatus>,
    #[serde(rename = "claim_amount_usdt", skip_serializing_if = "Option::is_none")]
    pub claim_amount_usdt: Option<f64>,
    #[serde(rename = "expected_lease_id", skip_serializing_if = "Option::is_none")]
    pub expected_lease_id: Option<f64>,
    #[serde(rename = "last_pull_timestamp", skip_serializing_if = "Option::is_none")]
    pub last_pull_timestamp: Option<i32>,
    #[serde(rename = "preentitle_time_ok", skip_serializing_if = "Option::is_none")]
    pub preentitle_time_ok: Option<bool>,
    #[serde(rename = "recommended_action", skip_serializing_if = "Option::is_none")]
    pub recommended_action: Option<String>,
}

impl ReceiverUsdtTransferActionability {
    /// Receiver USDT deposits + actionability hints (preEntitle vs pull)  For each canonical TRC-20 USDT transfer into a deterministic receiver, this view shows: - whether the hub has already accounted for it (matching claim origin_id == tx_hash), - the latest observed receiver pull timestamp for (receiver_salt, token), and - whether `preEntitle` is still time-eligible (`transfer_ts > last_pull_ts`).  `recommended_action` is a best-effort operator hint: - 'already_accounted' => hub claim exists (origin pre-entitle or subjective pre-entitle) - 'pre_entitle'        => no claim yet and pre-entitle timing is still allowed - 'pull'               => no claim yet and a later pull timestamp suggests pre-entitle would revert
    pub fn new() -> ReceiverUsdtTransferActionability {
        ReceiverUsdtTransferActionability {
            chain_id: None,
            token: None,
            receiver_salt: None,
            sender: None,
            recipient: None,
            amount: None,
            block_number: None,
            block_timestamp: None,
            block_time: None,
            block_hash: None,
            tx_hash: None,
            log_index: None,
            claim_origin: None,
            claim_lease_id: None,
            claim_id: None,
            claim_status: None,
            claim_amount_usdt: None,
            expected_lease_id: None,
            last_pull_timestamp: None,
            preentitle_time_ok: None,
            recommended_action: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClaimStatus {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "filled")]
    Filled,
}

impl Default for ClaimStatus {
    fn default() -> ClaimStatus {
        Self::Created
    }
}

