/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiverUsdtIndexerStatus {
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<String>,
    #[serde(rename = "tail_next_block", skip_serializing_if = "Option::is_none")]
    pub tail_next_block: Option<i64>,
    #[serde(rename = "tail_updated_at", skip_serializing_if = "Option::is_none")]
    pub tail_updated_at: Option<String>,
    #[serde(rename = "min_backfill_next_block", skip_serializing_if = "Option::is_none")]
    pub min_backfill_next_block: Option<i64>,
    #[serde(rename = "receiver_count", skip_serializing_if = "Option::is_none")]
    pub receiver_count: Option<i64>,
    #[serde(rename = "backfill_pending_receivers", skip_serializing_if = "Option::is_none")]
    pub backfill_pending_receivers: Option<i64>,
    #[serde(rename = "watchlist_updated_at", skip_serializing_if = "Option::is_none")]
    pub watchlist_updated_at: Option<String>,
}

impl ReceiverUsdtIndexerStatus {
    pub fn new() -> ReceiverUsdtIndexerStatus {
        ReceiverUsdtIndexerStatus {
            stream: None,
            tail_next_block: None,
            tail_updated_at: None,
            min_backfill_next_block: None,
            receiver_count: None,
            backfill_pending_receivers: None,
            watchlist_updated_at: None,
        }
    }
}

