/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiverUsdtBalances {
    #[serde(rename = "receiver_salt", skip_serializing_if = "Option::is_none")]
    pub receiver_salt: Option<String>,
    #[serde(rename = "receiver", skip_serializing_if = "Option::is_none")]
    pub receiver: Option<String>,
    #[serde(rename = "receiver_evm", skip_serializing_if = "Option::is_none")]
    pub receiver_evm: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "incoming_amount", skip_serializing_if = "Option::is_none")]
    pub incoming_amount: Option<serde_json::Number>,
    #[serde(rename = "pulled_amount", skip_serializing_if = "Option::is_none")]
    pub pulled_amount: Option<serde_json::Number>,
    #[serde(rename = "balance_amount", skip_serializing_if = "Option::is_none")]
    pub balance_amount: Option<serde_json::Number>,
}

impl ReceiverUsdtBalances {
    pub fn new() -> ReceiverUsdtBalances {
        ReceiverUsdtBalances {
            receiver_salt: None,
            receiver: None,
            receiver_evm: None,
            token: None,
            incoming_amount: None,
            pulled_amount: None,
            balance_amount: None,
        }
    }
}

