/*
 * Untron Indexed Data API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamIngestSummary {
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<String>,
    #[serde(rename = "applied_through_seq", skip_serializing_if = "Option::is_none")]
    pub applied_through_seq: Option<i64>,
    #[serde(rename = "tip", skip_serializing_if = "Option::is_none")]
    pub tip: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "max_event_seq", skip_serializing_if = "Option::is_none")]
    pub max_event_seq: Option<i64>,
    #[serde(rename = "max_block_number", skip_serializing_if = "Option::is_none")]
    pub max_block_number: Option<i64>,
    #[serde(rename = "max_block_timestamp", skip_serializing_if = "Option::is_none")]
    pub max_block_timestamp: Option<i64>,
    #[serde(rename = "max_block_time", skip_serializing_if = "Option::is_none")]
    pub max_block_time: Option<String>,
    #[serde(rename = "is_projection_caught_up", skip_serializing_if = "Option::is_none")]
    pub is_projection_caught_up: Option<bool>,
}

impl StreamIngestSummary {
    pub fn new() -> StreamIngestSummary {
        StreamIngestSummary {
            stream: None,
            applied_through_seq: None,
            tip: None,
            updated_at: None,
            max_event_seq: None,
            max_block_number: None,
            max_block_timestamp: None,
            max_block_time: None,
            is_projection_caught_up: None,
        }
    }
}

