/*
 * Untron V3 Indexer API
 *
 * Read-only HTTP API served by PostgREST.  This schema contains only views. Each view exposes either: - canonical raw event data (`api.event_appended`), or - \"current state\" derived from events (views over `hub.*` and `ctl.*` versioned tables), or - append-only ledgers for actions (views over `hub.*_ledger` and `ctl.*_ledger` tables).  The underlying protocol is Untron V3: - hub (EVM): `UntronV3Index` emits a hash-chained event stream - controller (Tron): `UntronControllerIndex` emits a hash-chained event stream  All state shown here is derived deterministically from those streams and is reorg-safe.
 *
 * The version of the OpenAPI document: 14.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnaccountedReceiverUsdtTransfers : Unaccounted receiver USDT deposits  Tron TRC-20 Transfer logs not yet reflected as hub claims  Rows in this view correspond to canonical TRC-20 USDT transfers into deterministic receivers that do NOT yet have a hub-side claim with `origin in (pre-entitle, subjective pre-entitle)` matching `origin_id = tx_hash`.  This view is intended for operators to identify deposits that may require action (preEntitle or receiver pull).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnaccountedReceiverUsdtTransfers {
    #[serde(rename = "chain_id", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<i64>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "receiver_salt", skip_serializing_if = "Option::is_none")]
    pub receiver_salt: Option<String>,
    #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
    pub sender: Option<String>,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<serde_json::Number>,
    #[serde(rename = "block_number", skip_serializing_if = "Option::is_none")]
    pub block_number: Option<i64>,
    #[serde(rename = "block_timestamp", skip_serializing_if = "Option::is_none")]
    pub block_timestamp: Option<i64>,
    #[serde(rename = "block_time", skip_serializing_if = "Option::is_none")]
    pub block_time: Option<String>,
    #[serde(rename = "block_hash", skip_serializing_if = "Option::is_none")]
    pub block_hash: Option<String>,
    #[serde(rename = "tx_hash", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<String>,
    #[serde(rename = "log_index", skip_serializing_if = "Option::is_none")]
    pub log_index: Option<i64>,
    #[serde(rename = "expected_lease_id", skip_serializing_if = "Option::is_none")]
    pub expected_lease_id: Option<serde_json::Number>,
}

impl UnaccountedReceiverUsdtTransfers {
    /// Unaccounted receiver USDT deposits  Tron TRC-20 Transfer logs not yet reflected as hub claims  Rows in this view correspond to canonical TRC-20 USDT transfers into deterministic receivers that do NOT yet have a hub-side claim with `origin in (pre-entitle, subjective pre-entitle)` matching `origin_id = tx_hash`.  This view is intended for operators to identify deposits that may require action (preEntitle or receiver pull).
    pub fn new() -> UnaccountedReceiverUsdtTransfers {
        UnaccountedReceiverUsdtTransfers {
            chain_id: None,
            token: None,
            receiver_salt: None,
            sender: None,
            recipient: None,
            amount: None,
            block_number: None,
            block_timestamp: None,
            block_time: None,
            block_hash: None,
            tx_hash: None,
            log_index: None,
            expected_lease_id: None,
        }
    }
}

